name: C/C++

on:
  push:
    branches: [master, develop, feature/**, change/**, hotfix/**]
    tags: [v*]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: apt-get install valgrind
        run: sudo apt-get install valgrind

      - name: checkout
        uses: actions/checkout@v2

      - name: make
        run: make
      - name: make test
        run: make test
